name: flutter_firebase
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add the dependency for the Firebase Core Flutter SDK

  cupertino_icons: ^1.0.2
  provider: ^4.1.3
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  #url_launcher: ^5.4.0    # Good, any 5.4.x version where x >= 0 works.
  #image_picker: '5.4.3'   # Not so good, only version 5.4.3 works.

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


